In [1]:
from sklearn.preprocessing import LabelBinarizer  # can be used on num data too. similar to onehot but more preferred
import numpy as np
import pandas as pd

In [2]:
num_binarizer = LabelBinarizer()

In [3]:
num_binarizer.fit(["monday", "Tuesday", "Wednesday"])

LabelBinarizer()

In [4]:
num_binarizer.classes_

array(['Tuesday', 'Wednesday', 'monday'], dtype='<U9')

In [5]:
num_binarizer.transform(["monday", "Tuesday", "Wednesday"])

array([[0, 0, 1],
       [1, 0, 0],
       [0, 1, 0]])

In [6]:
# labelBinarizer with custom +ve and -ve identifier set to 1 and -1
temp_binarizer = LabelBinarizer(neg_label=-1, pos_label=1, sparse_output=False)

In [7]:
temperature = ["cold","cold", "warm", "cold", "hot", "hot", "warm", "cold"]

temp_binarizer.fit_transform(temperature)

array([[ 1, -1, -1],
       [ 1, -1, -1],
       [-1, -1,  1],
       [ 1, -1, -1],
       [-1,  1, -1],
       [-1,  1, -1],
       [-1, -1,  1],
       [ 1, -1, -1]])

In [8]:
temp_binarizer.classes_

array(['cold', 'hot', 'warm'], dtype='<U4')

In [9]:
# with just bin classes it works like LabelEncoder
binary_encoder = LabelBinarizer()

binary_encoder.fit_transform(["Male", "Female"])

array([[1],
       [0]])

In [10]:
binary_encoder.classes_

array(['Female', 'Male'], dtype='<U6')